### ISSUE TITLE
avr\sleep.h: No such file or directory

### ISSUE THREAD

**Issue by whyameye** [LaZsolt/lgt8fx#1]
When trying example `idleWakePeriodic` with latest from master (commit 5c1bc02412659c62d4cb608946e6561b56d38de5) on MacOS Arduino v2.1.0 board LGT8F328P-LQFP48 I get:
```In file included from /Users/***/Documents/Arduino/libraries/lgt_lowpower/src/lgt_LowPower.cpp:52:0:
/Users/***/Documents/Arduino/libraries/lgt_lowpower/src/lgt8fx_sleep.h:39:10: fatal error: avr\sleep.h: No such file or directory
 #include <avr\sleep.h>```

**Comment by whyameye** [comment]
the workaround appears to be to change the backslashes (\) to forward slashes (/) in the includes for `lgt8fx_sleep.h` and `lgt8fx_power.h`

**Comment by LaZsolt** [comment]
> the workaround appears to be to change the backslashes () to forward slashes (/) in the includes for `lgt8fx_sleep.h` and `lgt8fx_power.h`

I apologize for the late response. You are right. I'll correct these mistakes,

**Comment by LaZsolt** [comment]
The bug has been fixed.
